export const recipeConstants = {
  // RECIPE_ADD_REQUEST: 'RECIPE_ADD_REQUEST',
  // RECIPE_ADD_SUCCESS: 'RECIPE_ADD_SUCCESS',
  // RECIPE_ADD_FAILURE: 'RECIPE_ADD_FAILURE'
  RECIPE_GET_RECIPES: 'RECIPE_GET_RECIPES',
  RECIPE_GET_RECIPE: 'RECIPE_GET_RECIPE',

  RECIPE_ADD_BASIC_INFO_REQUEST: 'RECIPE_ADD_BASIC_INFO_REQUEST',
  RECIPE_ADD_BASIC_INFO_SUCCESS: 'RECIPE_ADD_BASIC_INFO_SUCCESS',
  RECIPE_ADD_BASIC_INFO_FAILURE: 'RECIPE_ADD_BASIC_INFO_FAILURE',

  RECIPE_ADD_MATERIAL_REQUEST: 'RECIPE_ADD_MATERIAL_REQUEST',
  RECIPE_ADD_MATERIAL_SUCCESS: 'RECIPE_ADD_MATERIAL_SUCCESS',
  RECIPE_ADD_MATERIAL_FAILURE: 'RECIPE_ADD_MATERIAL_FAILURE',

  RECIPE_ADD_STEP_REQUEST: 'RECIPE_ADD_STEP_REQUEST',
  RECIPE_ADD_STEP_SUCCESS: 'RECIPE_ADD_STEP_SUCCESS',
  RECIPE_ADD_STEP_FAILURE: 'RECIPE_ADD_STEP_FAILURE',
  RECIPE_ADD_STEP_FINISH: 'RECIPE_ADD_STEP_FINISH',

  RECIPE_ADD_FINISH_REQUEST: 'RECIPE_ADD_FINISH_REQUEST',
  RECIPE_ADD_FINISH_SUCCESS: 'RECIPE_ADD_FINISH_SUCCESS',
  RECIPE_ADD_FINISH_FAILURE: 'RECIPE_ADD_FINISH_FAILURE',

  RECIPE_SEARCH: 'RECIPE_SEARCH',
  RECIPE_RESET_SEARCH: 'RECIPE_RESET_SEARCH',

  GET_RELATED_RECIPE: 'GET_RELATED_RECIPE',

  FILTER: 'FILTER',

  CLEAR: 'CLEAR'
}