export const recipeConstants = {
  // RECIPE_ADD_REQUEST: 'RECIPE_ADD_REQUEST',
  // RECIPE_ADD_SUCCESS: 'RECIPE_ADD_SUCCESS',
  // RECIPE_ADD_FAILURE: 'RECIPE_ADD_FAILURE'

  RECIPE_ADD_BASIC_INFO_REQUEST: 'RECIPE_ADD_BASIC_INFO_REQUEST',
  RECIPE_ADD_BASIC_INFO_SUCCESS: 'RECIPE_ADD_BASIC_INFO_SUCCESS',
  RECIPE_ADD_BASIC_INFO_FAILURE: 'RECIPE_ADD_BASIC_INFO_FAILURE',

  RECIPE_ADD_MATERIAL_REQUEST: 'RECIPE_ADD_MATERIAL_REQUEST',
  RECIPE_ADD_MATERIAL_SUCCESS: 'RECIPE_ADD_MATERIAL_SUCCESS',
  RECIPE_ADD_MATERIAL_FAILURE: 'RECIPE_ADD_MATERIAL_FAILURE',

  RECIPE_ADD_STEP_REQUEST: 'RECIPE_ADD_STEP_REQUEST',
  RECIPE_ADD_STEP_SUCCESS: 'RECIPE_ADD_STEP_SUCCESS',
  RECIPE_ADD_STEP_FAILURE: 'RECIPE_ADD_STEP_FAILURE',
  RECIPE_ADD_STEP_FINISH: 'RECIPE_ADD_STEP_FINISH',

  RECIPE_ADD_FINISH_REQUEST: 'RECIPE_ADD_FINISH_REQUEST',
  RECIPE_ADD_FINISH_SUCCESS: 'RECIPE_ADD_FINISH_SUCCESS',
  RECIPE_ADD_FINISH_FAILURE: 'RECIPE_ADD_FINISH_FAILURE'
}